name: Azure Deployment
run-name: Azure Deployment - Run: ${{ github.run_id}}
on: [push]
jobs:
  First-Stage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the first stage of the Azure deployment workflow."
        