# This workflow is triggered when an LOB commits a parameters file.
name: EaaS Deployment

on: 
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

run-name: "EaaS Deployment - Run: ${{ github.run_id }}"

jobs:
  First-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "This is the first stage of the EaaS deployment workflow."
  Deploy-Stage:
    name: Deploy EaaS
    uses: riwasa/demo-eaas-pattern/.github/workflows/eaas-deploy.yaml@main
    needs: First-Stage
    with:
      parameters_file: "lob.json"
    secrets:
      inherit
